help:
    @just --list

# Test if the flake looks syntactically correct.
test:
    nixos-rebuild dry-build --flake '.#'

# Install the flake on your box. Run as root.
install:
    nixos-rebuild switch --flake '.#'

# Update sources to latest versions.
update:
    nix flake update
