theme = "ayu_evolve"

[keys.normal]
# Colemak-friendly navigation
n = "move_visual_line_down"
e = "move_visual_line_up"
N = "join_selections"
A-N = "join_selections_space"
j = "move_next_word_end"
J = "move_next_long_word_end"
k = "search_next"
K = "search_prev"

";" = "command_mode"
":" = "collapse_selection"

C-n = "jump_view_down"
C-e = "jump_view_up"
C-h = "jump_view_left"
C-l = "jump_view_right"

[keys.normal."C-w"]
n = "jump_view_down"
C-n = "jump_view_down"
e = "jump_view_up"
C-e = "jump_view_up"
N = "swap_view_down"
E = "swap_view_up"

[keys.select]
# Colemak-friendly again
n = "extend_line_down"
e = "extend_line_up"
A-n = "shrink_selection"
A-e = "expand_selection"
k = "search_next"
K = "search_prev"

";" = "command_mode"
":" = "collapse_selection"
"A-:" = "flip_selections"

# Abbrev-like stuff
[keys.insert.C-k]
t = [":insert-output date +'%Y-%m-%d'", "move_char_right"]  # Insert datestamp
T = [":insert-output date +'%Y-%m-%d %H:%M'", "move_char_right"]  # Insert timestamp

[editor]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
